/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.bmob.im.demo;

public final class R {
    public static final class anim {
        public static int grow_from_bottom=0x7f040000;
        public static int shrink_from_top=0x7f040001;
    }
    public static final class attr {
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int centered=0x7f010006;
        /**  Screen edge padding. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int clipPadding=0x7f010011;
        /**  Length of the delay to fade the indicator. 
         <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fadeDelay=0x7f01001d;
        /**  Length of the indicator fade to transparent. 
         <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fadeLength=0x7f01001e;
        /**  Whether or not the selected indicator fades. 
         <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fades=0x7f01001c;
        /**  Color of the filled circle that represents the current page. 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fillColor=0x7f01000a;
        /**  Color of the footer line and indicator. 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int footerColor=0x7f010012;
        /**  Height of the indicator above the footer line. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int footerIndicatorHeight=0x7f010015;
        /**  Style of the indicator. Default is triangle. 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>triangle</code></td><td>1</td><td></td></tr>
<tr><td><code>underline</code></td><td>2</td><td></td></tr>
</table>
         */
        public static int footerIndicatorStyle=0x7f010014;
        /**  Left and right padding of the underline indicator. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int footerIndicatorUnderlinePadding=0x7f010016;
        /**  Height of the footer line. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int footerLineHeight=0x7f010013;
        /**  Padding between the bottom of the title and the footer. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int footerPadding=0x7f010017;
        /**  Width of the gap between each indicator line. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int gapWidth=0x7f010010;
        /**  Position of the line. 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bottom</code></td><td>0</td><td></td></tr>
<tr><td><code>top</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int linePosition=0x7f010018;
        /**  Width of each indicator line. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int lineWidth=0x7f01000f;
        /**  Color of the filled circles that represents pages. 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int pageColor=0x7f01000b;
        /**  Radius of the circles. This is also the spacing between circles. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int radius=0x7f01000c;
        /**  Whether or not the selected item is displayed as bold. 
         <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int selectedBold=0x7f010019;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int selectedColor=0x7f010007;
        /**  Whether or not the selected indicator snaps to the circles. 
         <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int snap=0x7f01000d;
        /**  Color of the open circles. 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int strokeColor=0x7f01000e;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int strokeWidth=0x7f010008;
        /**  Padding between titles when bumping into each other. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int titlePadding=0x7f01001a;
        /**  Padding between titles and the top of the View. 
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int topPadding=0x7f01001b;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int unselectedColor=0x7f010009;
        /**  Style of the circle indicator. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int vpiCirclePageIndicatorStyle=0x7f010000;
        /**  Style of the icon indicator's views. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int vpiIconPageIndicatorStyle=0x7f010001;
        /**  Style of the line indicator. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int vpiLinePageIndicatorStyle=0x7f010002;
        /**  Style of the tab indicator's tabs. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int vpiTabPageIndicatorStyle=0x7f010004;
        /**  Style of the title indicator. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int vpiTitlePageIndicatorStyle=0x7f010003;
        /**  Style of the underline indicator. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int vpiUnderlinePageIndicatorStyle=0x7f010005;
    }
    public static final class bool {
        public static int default_circle_indicator_centered=0x7f080000;
        public static int default_circle_indicator_snap=0x7f080001;
        public static int default_line_indicator_centered=0x7f080002;
        public static int default_title_indicator_selected_bold=0x7f080003;
        public static int default_underline_indicator_fades=0x7f080004;
    }
    public static final class color {
        public static int base_action_bar_title_color=0x7f070012;
        public static int base_actionbar_bg=0x7f070011;
        public static int base_bg=0x7f07001a;
        public static int base_color_text_black=0x7f070016;
        public static int base_color_text_gray=0x7f070017;
        public static int base_color_text_white=0x7f070018;
        public static int base_menu_left_bg=0x7f070014;
        public static int base_tab_indicator_text_color=0x7f070013;
        public static int c_f98800=0x7f070028;
        public static int color_bottom_bg=0x7f07001f;
        public static int color_bottom_text_normal=0x7f070020;
        public static int color_bottom_text_press=0x7f070021;
        /**  zxing 
         */
        public static int color_half_transparent=0x7f07001b;
        public static int color_theme=0x7f070027;
        public static int color_transparent_bg=0x7f07001c;
        public static int color_transparent_bg1=0x7f07001d;
        public static int common_bg=0x7f07002b;
        public static int default_circle_indicator_fill_color=0x7f070008;
        public static int default_circle_indicator_page_color=0x7f070009;
        public static int default_circle_indicator_stroke_color=0x7f07000a;
        public static int default_line_indicator_selected_color=0x7f07000b;
        public static int default_line_indicator_unselected_color=0x7f07000c;
        public static int default_title_indicator_footer_color=0x7f07000d;
        public static int default_title_indicator_selected_color=0x7f07000e;
        public static int default_title_indicator_text_color=0x7f07000f;
        public static int default_underline_indicator_selected_color=0x7f070010;
        public static int dialog_color_title=0x7f070029;
        public static int divider_list=0x7f070024;
        public static int guide_color=0x7f07002a;
        public static int home_item_color_bg=0x7f070019;
        public static int msg_chat_bg=0x7f070025;
        /**  emot 
         */
        public static int msg_emote_divider=0x7f07001e;
        public static int pull_refresh_textview=0x7f070015;
        public static int text_gray=0x7f070022;
        public static int theme_bg_color=0x7f070026;
        public static int transparent=0x7f070023;
        public static int vpi__background_holo_dark=0x7f070000;
        public static int vpi__background_holo_light=0x7f070001;
        public static int vpi__bright_foreground_disabled_holo_dark=0x7f070004;
        public static int vpi__bright_foreground_disabled_holo_light=0x7f070005;
        public static int vpi__bright_foreground_holo_dark=0x7f070002;
        public static int vpi__bright_foreground_holo_light=0x7f070003;
        public static int vpi__bright_foreground_inverse_holo_dark=0x7f070006;
        public static int vpi__bright_foreground_inverse_holo_light=0x7f070007;
        public static int vpi__dark_theme=0x7f07002c;
        public static int vpi__light_theme=0x7f07002d;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static int activity_horizontal_margin=0x7f0a000d;
        public static int activity_vertical_margin=0x7f0a000e;
        public static int base_action_bar_height=0x7f0a0012;
        public static int base_action_bar_title_size=0x7f0a0013;
        public static int base_line_width=0x7f0a001b;
        public static int base_line_width_1=0x7f0a0019;
        public static int base_line_width_2=0x7f0a001a;
        public static int base_scrollview_top_height=0x7f0a0015;
        public static int default_circle_indicator_radius=0x7f0a0000;
        public static int default_circle_indicator_stroke_width=0x7f0a0001;
        public static int default_line_indicator_gap_width=0x7f0a0003;
        public static int default_line_indicator_line_width=0x7f0a0002;
        public static int default_line_indicator_stroke_width=0x7f0a0004;
        public static int default_title_indicator_clip_padding=0x7f0a0005;
        public static int default_title_indicator_footer_indicator_height=0x7f0a0007;
        public static int default_title_indicator_footer_indicator_underline_padding=0x7f0a0008;
        public static int default_title_indicator_footer_line_height=0x7f0a0006;
        public static int default_title_indicator_footer_padding=0x7f0a0009;
        public static int default_title_indicator_text_size=0x7f0a000a;
        public static int default_title_indicator_title_padding=0x7f0a000b;
        public static int default_title_indicator_top_padding=0x7f0a000c;
        public static int margin_chat_top=0x7f0a0022;
        public static int message_top_height=0x7f0a0021;
        public static int register_margin=0x7f0a0014;
        public static int score_item_height=0x7f0a0020;
        public static int tab_height=0x7f0a0018;
        public static int tab_padding_left_right=0x7f0a0017;
        public static int tab_padding_top_bottom=0x7f0a0016;
        public static int text_size_large=0x7f0a0011;
        public static int text_size_medium=0x7f0a0010;
        public static int text_size_small=0x7f0a000f;
        public static int time_line_content_left_margin=0x7f0a001e;
        public static int time_line_content_right_margin=0x7f0a001f;
        public static int time_line_line_left_margin=0x7f0a001c;
        public static int time_line_line_width=0x7f0a001d;
    }
    public static final class drawable {
        public static int about_bottom_bg=0x7f020000;
        public static int about_mid_bg=0x7f020001;
        public static int about_top_bg=0x7f020002;
        public static int arrow=0x7f020003;
        public static int base_action_bar_add_bg_n=0x7f020004;
        public static int base_action_bar_add_bg_p=0x7f020005;
        public static int base_action_bar_add_bg_selector=0x7f020006;
        public static int base_action_bar_back_bg_n=0x7f020007;
        public static int base_action_bar_back_bg_p=0x7f020008;
        public static int base_action_bar_back_bg_selector=0x7f020009;
        public static int base_action_bar_more_bg_n=0x7f02000a;
        public static int base_action_bar_more_bg_p=0x7f02000b;
        public static int base_action_bar_more_bg_selector=0x7f02000c;
        public static int base_action_bar_true_bg_n=0x7f02000d;
        public static int base_action_bar_true_bg_p=0x7f02000e;
        public static int base_action_bar_true_bg_selector=0x7f02000f;
        public static int base_comment_emo_bar=0x7f020010;
        public static int base_dialog_bg=0x7f020011;
        public static int base_edit_input=0x7f020012;
        public static int base_horization_line=0x7f020013;
        public static int base_horizontal_line=0x7f020014;
        public static int base_horizontal_line_red=0x7f020015;
        public static int bg_chat_emote_selector=0x7f020016;
        public static int btn_chat_add_camera_selector=0x7f020017;
        public static int btn_chat_add_location_selector=0x7f020018;
        public static int btn_chat_add_picture_selector=0x7f020019;
        public static int btn_chat_add_selector=0x7f02001a;
        public static int btn_chat_emo_selector=0x7f02001b;
        public static int btn_chat_fail_resend=0x7f02001c;
        public static int btn_chat_keyboard_selector=0x7f02001d;
        public static int btn_chat_send_selector=0x7f02001e;
        public static int btn_chat_voice_selector=0x7f02001f;
        public static int btn_clear=0x7f020020;
        public static int btn_emo_delete_selector=0x7f020021;
        public static int btn_emote_selector=0x7f020022;
        public static int btn_login_n=0x7f020023;
        public static int btn_login_p=0x7f020024;
        public static int btn_login_selector=0x7f020025;
        public static int btn_logout_n=0x7f020026;
        public static int btn_logout_p=0x7f020027;
        public static int btn_logout_selector=0x7f020028;
        public static int btn_selector=0x7f020029;
        public static int btn_send_n=0x7f02002a;
        public static int btn_send_press=0x7f02002b;
        public static int btn_send_selector=0x7f02002c;
        public static int button_bg=0x7f02002d;
        public static int button_normal_shape=0x7f02002e;
        public static int button_selector_shape=0x7f02002f;
        public static int chat_add_camera_normal=0x7f020030;
        public static int chat_add_camera_press=0x7f020031;
        public static int chat_add_location_normal=0x7f020032;
        public static int chat_add_location_press=0x7f020033;
        public static int chat_add_normal=0x7f020034;
        public static int chat_add_picture_normal=0x7f020035;
        public static int chat_add_picture_press=0x7f020036;
        public static int chat_add_press=0x7f020037;
        public static int chat_emo_normal=0x7f020038;
        public static int chat_emo_press=0x7f020039;
        public static int chat_fail_resend_normal=0x7f02003a;
        public static int chat_fail_resend_press=0x7f02003b;
        public static int chat_keyboard_normal=0x7f02003c;
        public static int chat_keyboard_press=0x7f02003d;
        public static int chat_left_qp=0x7f02003e;
        public static int chat_right_qp=0x7f02003f;
        public static int chat_send_n=0x7f020040;
        public static int chat_send_p=0x7f020041;
        public static int chat_time_block=0x7f020042;
        public static int chat_voice_bg=0x7f020043;
        public static int chat_voice_normal=0x7f020044;
        public static int chat_voice_press=0x7f020045;
        public static int contact_list_buddy_item_bg=0x7f020046;
        public static int default_head=0x7f020047;
        public static int dialog_btn_selector=0x7f020048;
        public static int dialog_shape_normal=0x7f020049;
        public static int dialog_shape_pressed=0x7f02004a;
        public static int emo_delete_normal=0x7f02004b;
        public static int emo_delete_press=0x7f02004c;
        public static int head=0x7f02004d;
        public static int ic_launcher=0x7f02004e;
        public static int icon_contact_normal=0x7f02004f;
        public static int icon_contact_press=0x7f020050;
        public static int icon_geo=0x7f020051;
        public static int icon_message_normal=0x7f020052;
        public static int icon_message_press=0x7f020053;
        public static int icon_msg_search=0x7f020054;
        public static int icon_set_normal=0x7f020055;
        public static int icon_set_press=0x7f020056;
        public static int input_bg=0x7f020057;
        public static int ios7_btn=0x7f020058;
        public static int list_conversation_press=0x7f020059;
        public static int list_newmessage2=0x7f02005a;
        public static int location_default=0x7f02005b;
        public static int login_bg=0x7f02005c;
        public static int login_icon_account=0x7f02005d;
        public static int login_icon_password=0x7f02005e;
        public static int login_logo=0x7f02005f;
        public static int mini_avatar_shadow=0x7f020060;
        public static int mm_listitem=0x7f020061;
        public static int mm_listitem_grey=0x7f020062;
        public static int mm_listitem_grey_normal=0x7f020063;
        public static int mm_listitem_pressed=0x7f020064;
        public static int mm_listitem_simple=0x7f020065;
        public static int msg_tips=0x7f020066;
        public static int new_friends_icon=0x7f020067;
        public static int off=0x7f020068;
        public static int on=0x7f020069;
        public static int pop_bg=0x7f02006a;
        public static int pop_bg_press=0x7f02006b;
        public static int progress_black=0x7f02006c;
        public static int recent_message_text_color_selector=0x7f02006d;
        public static int recent_name_text_color_selector=0x7f02006e;
        public static int refresh_black=0x7f02006f;
        public static int register_bottom_arrow=0x7f020070;
        public static int search_clear=0x7f020071;
        public static int search_clear_normal=0x7f020072;
        public static int search_clear_pressed=0x7f020073;
        public static int tab_contact_btn=0x7f020074;
        public static int tab_message_btn=0x7f020075;
        public static int tab_set_btn=0x7f020076;
        public static int tab_textcolor=0x7f020077;
        public static int top_bar=0x7f020078;
        public static int ue00e=0x7f020079;
        public static int ue056=0x7f02007a;
        public static int ue057=0x7f02007b;
        public static int ue058=0x7f02007c;
        public static int ue059=0x7f02007d;
        public static int ue105=0x7f02007e;
        public static int ue106=0x7f02007f;
        public static int ue107=0x7f020080;
        public static int ue108=0x7f020081;
        public static int ue11a=0x7f020082;
        public static int ue401=0x7f020083;
        public static int ue402=0x7f020084;
        public static int ue403=0x7f020085;
        public static int ue404=0x7f020086;
        public static int ue405=0x7f020087;
        public static int ue406=0x7f020088;
        public static int ue407=0x7f020089;
        public static int ue408=0x7f02008a;
        public static int ue409=0x7f02008b;
        public static int ue40a=0x7f02008c;
        public static int ue40b=0x7f02008d;
        public static int ue40c=0x7f02008e;
        public static int ue40d=0x7f02008f;
        public static int ue40e=0x7f020090;
        public static int ue40f=0x7f020091;
        public static int ue410=0x7f020092;
        public static int ue411=0x7f020093;
        public static int ue412=0x7f020094;
        public static int ue413=0x7f020095;
        public static int ue414=0x7f020096;
        public static int ue415=0x7f020097;
        public static int ue416=0x7f020098;
        public static int ue417=0x7f020099;
        public static int ue418=0x7f02009a;
        public static int ue41f=0x7f02009b;
        public static int ue421=0x7f02009c;
        public static int user_add_top_bg=0x7f02009d;
        public static int v2_gallery_contacts_dialog_background=0x7f02009e;
        public static int v2_sortlistview_sidebar_background=0x7f02009f;
        public static int vpi__tab_indicator=0x7f0200a0;
        public static int vpi__tab_selected_focused_holo=0x7f0200a1;
        public static int vpi__tab_selected_holo=0x7f0200a2;
        public static int vpi__tab_selected_pressed_holo=0x7f0200a3;
        public static int vpi__tab_unselected_focused_holo=0x7f0200a4;
        public static int vpi__tab_unselected_holo=0x7f0200a5;
        public static int vpi__tab_unselected_pressed_holo=0x7f0200a6;
    }
    public static final class id {
        public static int action_settings=0x7f06008d;
        public static int alpha=0x7f060074;
        public static int avatar=0x7f06005f;
        public static int bmapView=0x7f06000b;
        public static int bottom=0x7f060003;
        public static int btn_add=0x7f06001b;
        public static int btn_back=0x7f06002f;
        public static int btn_chat=0x7f06001e;
        public static int btn_chat_add=0x7f06004f;
        public static int btn_chat_emo=0x7f060050;
        public static int btn_chat_keyboard=0x7f060054;
        public static int btn_chat_send=0x7f060055;
        public static int btn_chat_voice=0x7f060053;
        public static int btn_contract=0x7f060015;
        public static int btn_delete=0x7f06001f;
        public static int btn_login=0x7f06000f;
        public static int btn_logout=0x7f060021;
        public static int btn_message=0x7f060013;
        public static int btn_query_contacts=0x7f06001c;
        public static int btn_register=0x7f060010;
        public static int btn_search=0x7f060007;
        public static int btn_set=0x7f060017;
        public static int btn_speak=0x7f060052;
        public static int btn_update=0x7f060020;
        public static int common_actionbar=0x7f060005;
        public static int dialog=0x7f06003c;
        public static int dialog_bottom=0x7f06007e;
        public static int dialog_contentPanel=0x7f06007b;
        public static int dialog_custom=0x01010000;
        public static int dialog_customPanel=0x7f06007d;
        public static int dialog_leftspacer=0x7f06007f;
        public static int dialog_message=0x7f06007c;
        public static int dialog_negativebutton=0x7f060080;
        public static int dialog_positivebutton=0x7f060081;
        public static int dialog_rightspacer=0x7f060082;
        public static int dialog_title=0x7f060079;
        public static int dialog_titleicon=0x7f060078;
        public static int dialog_top=0x7f060077;
        public static int edit_add=0x7f06001a;
        public static int edit_nick=0x7f060031;
        public static int edit_user_comment=0x7f060051;
        public static int et_email=0x7f060023;
        public static int et_find_name=0x7f060006;
        public static int et_msg_search=0x7f06003a;
        public static int et_nickname=0x7f060022;
        public static int et_password=0x7f06000e;
        public static int et_username=0x7f06000d;
        public static int fragment_container=0x7f060018;
        public static int fram=0x7f060071;
        public static int frame_new=0x7f06005c;
        public static int gridview=0x7f06005a;
        public static int header_htv_subtitle=0x7f060035;
        public static int header_ib_imagebutton=0x7f060038;
        public static int header_layout_imagebuttonlayout=0x7f060037;
        public static int header_layout_leftview_container=0x7f060033;
        public static int header_layout_middleview_container=0x7f060034;
        public static int header_layout_rightview_container=0x7f060036;
        public static int img_friend_avatar=0x7f060061;
        public static int iv_arraw=0x7f060027;
        public static int iv_avatar=0x7f060064;
        public static int iv_close_notification=0x7f060043;
        public static int iv_close_vibrate=0x7f06004a;
        public static int iv_close_voice=0x7f060046;
        public static int iv_contact_tips=0x7f060016;
        public static int iv_fail_resend=0x7f060069;
        public static int iv_icon=0x7f06000c;
        public static int iv_msg_tips=0x7f06005d;
        public static int iv_nickarraw=0x7f06002a;
        public static int iv_open_notification=0x7f060042;
        public static int iv_open_vibrate=0x7f060049;
        public static int iv_open_voice=0x7f060045;
        public static int iv_picture=0x7f060065;
        public static int iv_recent_avatar=0x7f06006b;
        public static int iv_recent_tips=0x7f060014;
        public static int iv_set_avator=0x7f060026;
        public static int layout_add=0x7f060059;
        public static int layout_all=0x7f060024;
        public static int layout_black_tips=0x7f060030;
        public static int layout_blacklist=0x7f060040;
        public static int layout_choose=0x7f060076;
        public static int layout_emo=0x7f060057;
        public static int layout_gender=0x7f06002d;
        public static int layout_head=0x7f060025;
        public static int layout_info=0x7f06003f;
        public static int layout_list=0x7f060039;
        public static int layout_location=0x7f060067;
        public static int layout_more=0x7f060056;
        public static int layout_name=0x7f06002b;
        public static int layout_new=0x7f06005b;
        public static int layout_nick=0x7f060028;
        public static int layout_photo=0x7f060075;
        public static int list=0x7f06003e;
        public static int list_blacklist=0x7f060009;
        public static int list_friends=0x7f06003b;
        public static int list_newfriend=0x7f060019;
        public static int list_search=0x7f060008;
        public static int mListView=0x7f06000a;
        public static int mainLayout=0x7f060011;
        public static int main_bottom=0x7f060012;
        public static int name=0x7f060060;
        public static int none=0x7f060000;
        public static int pager_emo=0x7f060058;
        public static int pagerview=0x7f060032;
        public static int photoview=0x7f060072;
        public static int progress=0x7f060073;
        public static int progress_load=0x7f060066;
        public static int right_letter=0x7f06003d;
        public static int rl_switch_notification=0x7f060041;
        public static int rl_switch_vibrate=0x7f060048;
        public static int rl_switch_voice=0x7f060044;
        public static int title_red_line=0x7f06007a;
        public static int top=0x7f060004;
        public static int triangle=0x7f060001;
        public static int tv_camera=0x7f06004d;
        public static int tv_contacts=0x7f06001d;
        public static int tv_friend_name=0x7f060062;
        public static int tv_location=0x7f06004e;
        public static int tv_message=0x7f060068;
        public static int tv_new_name=0x7f06005e;
        public static int tv_picture=0x7f06004c;
        public static int tv_recent_msg=0x7f06006d;
        public static int tv_recent_name=0x7f06006c;
        public static int tv_recent_time=0x7f06006e;
        public static int tv_recent_unread=0x7f06006f;
        public static int tv_send_status=0x7f06006a;
        public static int tv_set_gender=0x7f06002e;
        public static int tv_set_name=0x7f06002c;
        public static int tv_set_nick=0x7f060029;
        public static int tv_time=0x7f060063;
        public static int underline=0x7f060002;
        public static int v_face_text=0x7f060070;
        public static int view1=0x7f060047;
        public static int view2=0x7f06004b;
        public static int xlistview_footer_content=0x7f060083;
        public static int xlistview_footer_hint_textview=0x7f060085;
        public static int xlistview_footer_progressbar=0x7f060084;
        public static int xlistview_header_arrow=0x7f06008b;
        public static int xlistview_header_content=0x7f060086;
        public static int xlistview_header_hint_textview=0x7f060088;
        public static int xlistview_header_progressbar=0x7f06008c;
        public static int xlistview_header_text=0x7f060087;
        public static int xlistview_header_time=0x7f06008a;
        public static int xlistview_header_time_label=0x7f060089;
    }
    public static final class integer {
        public static int default_circle_indicator_orientation=0x7f090000;
        public static int default_title_indicator_footer_indicator_style=0x7f090001;
        public static int default_title_indicator_line_position=0x7f090002;
        public static int default_underline_indicator_fade_delay=0x7f090003;
        public static int default_underline_indicator_fade_length=0x7f090004;
    }
    public static final class layout {
        public static int activity_add_contact=0x7f030000;
        public static int activity_blacklist=0x7f030001;
        public static int activity_chat=0x7f030002;
        public static int activity_location=0x7f030003;
        public static int activity_login=0x7f030004;
        public static int activity_main=0x7f030005;
        public static int activity_new_friend=0x7f030006;
        public static int activity_other=0x7f030007;
        public static int activity_register=0x7f030008;
        public static int activity_set_info=0x7f030009;
        public static int activity_set_updateinfo=0x7f03000a;
        public static int activity_showpicture=0x7f03000b;
        public static int activity_splash=0x7f03000c;
        public static int common_header=0x7f03000d;
        public static int common_header_button=0x7f03000e;
        public static int common_header_rightbutton=0x7f03000f;
        public static int fragment_contacts=0x7f030010;
        public static int fragment_recent=0x7f030011;
        public static int fragment_set=0x7f030012;
        public static int include_action_bar=0x7f030013;
        public static int include_chat_add=0x7f030014;
        public static int include_chat_bottom_bar=0x7f030015;
        public static int include_emo_gridview=0x7f030016;
        public static int include_new_friend=0x7f030017;
        public static int item_add_friend=0x7f030018;
        public static int item_blacklist=0x7f030019;
        public static int item_chat_received_image=0x7f03001a;
        public static int item_chat_received_location=0x7f03001b;
        public static int item_chat_received_message=0x7f03001c;
        public static int item_chat_sent_image=0x7f03001d;
        public static int item_chat_sent_location=0x7f03001e;
        public static int item_chat_sent_message=0x7f03001f;
        public static int item_conversation=0x7f030020;
        public static int item_face_text=0x7f030021;
        public static int item_show_picture=0x7f030022;
        public static int item_user_friend=0x7f030023;
        public static int pop_showavator=0x7f030024;
        public static int v2_dialog_base=0x7f030025;
        public static int xlistview_footer=0x7f030026;
        public static int xlistview_header=0x7f030027;
    }
    public static final class menu {
        public static int main=0x7f0d0000;
    }
    public static final class raw {
        public static int notify=0x7f050000;
    }
    public static final class string {
        public static int action_settings=0x7f0c0001;
        public static int add_avator=0x7f0c0017;
        public static int add_gender=0x7f0c001b;
        public static int add_name=0x7f0c0019;
        public static int add_name_hint=0x7f0c001a;
        public static int add_nick=0x7f0c0018;
        public static int app_name=0x7f0c0000;
        public static int black_tips=0x7f0c0030;
        public static int blacklist=0x7f0c0029;
        public static int camera=0x7f0c002e;
        public static int chat=0x7f0c002a;
        public static int hello_world=0x7f0c0002;
        public static int location=0x7f0c002f;
        public static int login=0x7f0c0006;
        public static int login_account=0x7f0c000a;
        public static int login_email=0x7f0c000c;
        public static int login_email_hint=0x7f0c0005;
        public static int login_password_hint=0x7f0c0004;
        public static int login_pwd=0x7f0c000b;
        public static int login_username_hint=0x7f0c0003;
        public static int logout=0x7f0c0022;
        public static int longclick_speak=0x7f0c002c;
        public static int main_tab_contact=0x7f0c000f;
        public static int main_tab_recent=0x7f0c000e;
        public static int message_search_hint=0x7f0c000d;
        public static int mian_tab_set=0x7f0c0010;
        public static int network_tips=0x7f0c0025;
        public static int picture=0x7f0c002d;
        public static int pop_choose=0x7f0c0024;
        public static int pop_photo=0x7f0c0023;
        public static int register=0x7f0c0007;
        public static int register_txt1=0x7f0c0008;
        public static int register_txt2=0x7f0c0009;
        public static int send_state=0x7f0c002b;
        public static int set_blacklist=0x7f0c001e;
        public static int set_myinfo=0x7f0c001d;
        public static int set_notify=0x7f0c001c;
        public static int set_vibrate=0x7f0c0020;
        public static int set_voice=0x7f0c001f;
        public static int tips=0x7f0c0021;
        public static int toast_error_comfirm_password=0x7f0c0028;
        public static int toast_error_password_null=0x7f0c0026;
        public static int toast_error_username_null=0x7f0c0027;
        public static int xlistview_footer_hint_normal=0x7f0c0015;
        public static int xlistview_footer_hint_ready=0x7f0c0016;
        public static int xlistview_header_hint_loading=0x7f0c0013;
        public static int xlistview_header_hint_normal=0x7f0c0011;
        public static int xlistview_header_hint_ready=0x7f0c0012;
        public static int xlistview_header_last_time=0x7f0c0014;
    }
    public static final class style {
        public static int ActionBar=0x7f0b0007;
        public static int ActionBarTitle=0x7f0b0008;
        public static int Animations=0x7f0b001c;
        public static int Animations_GrowFromBottom=0x7f0b001d;
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static int AppBaseTheme=0x7f0b0005;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static int AppTheme=0x7f0b0006;
        public static int DialogWindowTitle=0x7f0b0020;
        public static int Register_Edit=0x7f0b001b;
        public static int Register_Input=0x7f0b001a;
        public static int Smile=0x7f0b000c;
        public static int Smile_Button=0x7f0b000e;
        public static int Smile_Button_logout=0x7f0b0015;
        public static int Smile_Button_theme=0x7f0b0014;
        public static int Smile_ImageView=0x7f0b0010;
        public static int Smile_ImageView_Photo_Large=0x7f0b0011;
        public static int Smile_ImageView_Photo_Middle=0x7f0b0012;
        public static int Smile_ImageView_Photo_Small=0x7f0b0013;
        public static int Smile_TextView=0x7f0b000d;
        public static int Smile_TextView__Black=0x7f0b0019;
        public static int Smile_TextView__Gray=0x7f0b0018;
        public static int Smile_TextView__Orange=0x7f0b0016;
        public static int Smile_TextView__White=0x7f0b0017;
        public static int Smile_View_margin=0x7f0b000f;
        /**  dialog 
         */
        public static int TextAppearance=0x7f0b001e;
        public static int TextAppearance_DialogWindowTitle=0x7f0b001f;
        public static int TextAppearance_TabPageIndicator=0x7f0b0003;
        public static int Theme_PageIndicatorDefaults=0x7f0b0000;
        public static int Widget=0x7f0b0001;
        public static int Widget_IconPageIndicator=0x7f0b0004;
        public static int Widget_TabPageIndicator=0x7f0b0002;
        public static int alert=0x7f0b0021;
        public static int chat_content_date_style=0x7f0b0009;
        public static int chat_text_date_style=0x7f0b000b;
        public static int chat_text_name_style=0x7f0b000a;
    }
    public static final class styleable {
        /** Attributes that can be used with a CirclePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CirclePageIndicator_android_background android:background}</code></td><td> View background </td></tr>
           <tr><td><code>{@link #CirclePageIndicator_android_orientation android:orientation}</code></td><td> Orientation of the indicator.</td></tr>
           <tr><td><code>{@link #CirclePageIndicator_centered com.bmob.im.demo:centered}</code></td><td> Whether or not the indicators should be centered.</td></tr>
           <tr><td><code>{@link #CirclePageIndicator_fillColor com.bmob.im.demo:fillColor}</code></td><td> Color of the filled circle that represents the current page.</td></tr>
           <tr><td><code>{@link #CirclePageIndicator_pageColor com.bmob.im.demo:pageColor}</code></td><td> Color of the filled circles that represents pages.</td></tr>
           <tr><td><code>{@link #CirclePageIndicator_radius com.bmob.im.demo:radius}</code></td><td> Radius of the circles.</td></tr>
           <tr><td><code>{@link #CirclePageIndicator_snap com.bmob.im.demo:snap}</code></td><td> Whether or not the selected indicator snaps to the circles.</td></tr>
           <tr><td><code>{@link #CirclePageIndicator_strokeColor com.bmob.im.demo:strokeColor}</code></td><td> Color of the open circles.</td></tr>
           <tr><td><code>{@link #CirclePageIndicator_strokeWidth com.bmob.im.demo:strokeWidth}</code></td><td> Width of the stroke used to draw the circles.</td></tr>
           </table>
           @see #CirclePageIndicator_android_background
           @see #CirclePageIndicator_android_orientation
           @see #CirclePageIndicator_centered
           @see #CirclePageIndicator_fillColor
           @see #CirclePageIndicator_pageColor
           @see #CirclePageIndicator_radius
           @see #CirclePageIndicator_snap
           @see #CirclePageIndicator_strokeColor
           @see #CirclePageIndicator_strokeWidth
         */
        public static final int[] CirclePageIndicator = {
            0x010100c4, 0x010100d4, 0x7f010006, 0x7f010008,
            0x7f01000a, 0x7f01000b, 0x7f01000c, 0x7f01000d,
            0x7f01000e
        };
        /**
          <p>
          @attr description
           View background 
          <p>This corresponds to the global attribute
          resource symbol {@link android.R.attr#background}.
          @attr name android:background
        */
        public static final int CirclePageIndicator_android_background = 1;
        /**
          <p>
          @attr description
           Orientation of the indicator. 
          <p>This corresponds to the global attribute
          resource symbol {@link android.R.attr#orientation}.
          @attr name android:orientation
        */
        public static final int CirclePageIndicator_android_orientation = 0;
        /**
          <p>
          @attr description
           Whether or not the indicators should be centered. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:centered
        */
        public static final int CirclePageIndicator_centered = 2;
        /**
          <p>
          @attr description
           Color of the filled circle that represents the current page. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:fillColor
        */
        public static final int CirclePageIndicator_fillColor = 4;
        /**
          <p>
          @attr description
           Color of the filled circles that represents pages. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:pageColor
        */
        public static final int CirclePageIndicator_pageColor = 5;
        /**
          <p>
          @attr description
           Radius of the circles. This is also the spacing between circles. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:radius
        */
        public static final int CirclePageIndicator_radius = 6;
        /**
          <p>
          @attr description
           Whether or not the selected indicator snaps to the circles. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:snap
        */
        public static final int CirclePageIndicator_snap = 7;
        /**
          <p>
          @attr description
           Color of the open circles. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:strokeColor
        */
        public static final int CirclePageIndicator_strokeColor = 8;
        /**
          <p>
          @attr description
           Width of the stroke used to draw the circles. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:strokeWidth
        */
        public static final int CirclePageIndicator_strokeWidth = 3;
        /** Attributes that can be used with a LinePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #LinePageIndicator_android_background android:background}</code></td><td> View background </td></tr>
           <tr><td><code>{@link #LinePageIndicator_centered com.bmob.im.demo:centered}</code></td><td> Whether or not the indicators should be centered.</td></tr>
           <tr><td><code>{@link #LinePageIndicator_gapWidth com.bmob.im.demo:gapWidth}</code></td><td> Width of the gap between each indicator line.</td></tr>
           <tr><td><code>{@link #LinePageIndicator_lineWidth com.bmob.im.demo:lineWidth}</code></td><td> Width of each indicator line.</td></tr>
           <tr><td><code>{@link #LinePageIndicator_selectedColor com.bmob.im.demo:selectedColor}</code></td><td> Color of the selected line that represents the current page.</td></tr>
           <tr><td><code>{@link #LinePageIndicator_strokeWidth com.bmob.im.demo:strokeWidth}</code></td><td> Width of each indicator line's stroke.</td></tr>
           <tr><td><code>{@link #LinePageIndicator_unselectedColor com.bmob.im.demo:unselectedColor}</code></td><td> Color of the unselected lines that represent the pages.</td></tr>
           </table>
           @see #LinePageIndicator_android_background
           @see #LinePageIndicator_centered
           @see #LinePageIndicator_gapWidth
           @see #LinePageIndicator_lineWidth
           @see #LinePageIndicator_selectedColor
           @see #LinePageIndicator_strokeWidth
           @see #LinePageIndicator_unselectedColor
         */
        public static final int[] LinePageIndicator = {
            0x010100d4, 0x7f010006, 0x7f010007, 0x7f010008,
            0x7f010009, 0x7f01000f, 0x7f010010
        };
        /**
          <p>
          @attr description
           View background 
          <p>This corresponds to the global attribute
          resource symbol {@link android.R.attr#background}.
          @attr name android:background
        */
        public static final int LinePageIndicator_android_background = 0;
        /**
          <p>
          @attr description
           Whether or not the indicators should be centered. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:centered
        */
        public static final int LinePageIndicator_centered = 1;
        /**
          <p>
          @attr description
           Width of the gap between each indicator line. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:gapWidth
        */
        public static final int LinePageIndicator_gapWidth = 6;
        /**
          <p>
          @attr description
           Width of each indicator line. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:lineWidth
        */
        public static final int LinePageIndicator_lineWidth = 5;
        /**
          <p>
          @attr description
           Color of the selected line that represents the current page. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:selectedColor
        */
        public static final int LinePageIndicator_selectedColor = 2;
        /**
          <p>
          @attr description
           Width of each indicator line's stroke. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:strokeWidth
        */
        public static final int LinePageIndicator_strokeWidth = 3;
        /**
          <p>
          @attr description
           Color of the unselected lines that represent the pages. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:unselectedColor
        */
        public static final int LinePageIndicator_unselectedColor = 4;
        /** Attributes that can be used with a TitlePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TitlePageIndicator_android_background android:background}</code></td><td> View background </td></tr>
           <tr><td><code>{@link #TitlePageIndicator_android_textColor android:textColor}</code></td><td> Color of regular titles.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_android_textSize android:textSize}</code></td><td> Size of title text.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_clipPadding com.bmob.im.demo:clipPadding}</code></td><td> Screen edge padding.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerColor com.bmob.im.demo:footerColor}</code></td><td> Color of the footer line and indicator.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerIndicatorHeight com.bmob.im.demo:footerIndicatorHeight}</code></td><td> Height of the indicator above the footer line.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerIndicatorStyle com.bmob.im.demo:footerIndicatorStyle}</code></td><td> Style of the indicator.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerIndicatorUnderlinePadding com.bmob.im.demo:footerIndicatorUnderlinePadding}</code></td><td> Left and right padding of the underline indicator.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerLineHeight com.bmob.im.demo:footerLineHeight}</code></td><td> Height of the footer line.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_footerPadding com.bmob.im.demo:footerPadding}</code></td><td> Padding between the bottom of the title and the footer.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_linePosition com.bmob.im.demo:linePosition}</code></td><td> Position of the line.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_selectedBold com.bmob.im.demo:selectedBold}</code></td><td> Whether or not the selected item is displayed as bold.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_selectedColor com.bmob.im.demo:selectedColor}</code></td><td> Color of the selected title.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_titlePadding com.bmob.im.demo:titlePadding}</code></td><td> Padding between titles when bumping into each other.</td></tr>
           <tr><td><code>{@link #TitlePageIndicator_topPadding com.bmob.im.demo:topPadding}</code></td><td> Padding between titles and the top of the View.</td></tr>
           </table>
           @see #TitlePageIndicator_android_background
           @see #TitlePageIndicator_android_textColor
           @see #TitlePageIndicator_android_textSize
           @see #TitlePageIndicator_clipPadding
           @see #TitlePageIndicator_footerColor
           @see #TitlePageIndicator_footerIndicatorHeight
           @see #TitlePageIndicator_footerIndicatorStyle
           @see #TitlePageIndicator_footerIndicatorUnderlinePadding
           @see #TitlePageIndicator_footerLineHeight
           @see #TitlePageIndicator_footerPadding
           @see #TitlePageIndicator_linePosition
           @see #TitlePageIndicator_selectedBold
           @see #TitlePageIndicator_selectedColor
           @see #TitlePageIndicator_titlePadding
           @see #TitlePageIndicator_topPadding
         */
        public static final int[] TitlePageIndicator = {
            0x01010095, 0x01010098, 0x010100d4, 0x7f010007,
            0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014,
            0x7f010015, 0x7f010016, 0x7f010017, 0x7f010018,
            0x7f010019, 0x7f01001a, 0x7f01001b
        };
        /**
          <p>
          @attr description
           View background 
          <p>This corresponds to the global attribute
          resource symbol {@link android.R.attr#background}.
          @attr name android:background
        */
        public static final int TitlePageIndicator_android_background = 2;
        /**
          <p>
          @attr description
           Color of regular titles. 
          <p>This corresponds to the global attribute
          resource symbol {@link android.R.attr#textColor}.
          @attr name android:textColor
        */
        public static final int TitlePageIndicator_android_textColor = 1;
        /**
          <p>
          @attr description
           Size of title text. 
          <p>This corresponds to the global attribute
          resource symbol {@link android.R.attr#textSize}.
          @attr name android:textSize
        */
        public static final int TitlePageIndicator_android_textSize = 0;
        /**
          <p>
          @attr description
           Screen edge padding. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:clipPadding
        */
        public static final int TitlePageIndicator_clipPadding = 4;
        /**
          <p>
          @attr description
           Color of the footer line and indicator. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:footerColor
        */
        public static final int TitlePageIndicator_footerColor = 5;
        /**
          <p>
          @attr description
           Height of the indicator above the footer line. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:footerIndicatorHeight
        */
        public static final int TitlePageIndicator_footerIndicatorHeight = 8;
        /**
          <p>
          @attr description
           Style of the indicator. Default is triangle. 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>triangle</code></td><td>1</td><td></td></tr>
<tr><td><code>underline</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:footerIndicatorStyle
        */
        public static final int TitlePageIndicator_footerIndicatorStyle = 7;
        /**
          <p>
          @attr description
           Left and right padding of the underline indicator. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:footerIndicatorUnderlinePadding
        */
        public static final int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
        /**
          <p>
          @attr description
           Height of the footer line. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:footerLineHeight
        */
        public static final int TitlePageIndicator_footerLineHeight = 6;
        /**
          <p>
          @attr description
           Padding between the bottom of the title and the footer. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:footerPadding
        */
        public static final int TitlePageIndicator_footerPadding = 10;
        /**
          <p>
          @attr description
           Position of the line. 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bottom</code></td><td>0</td><td></td></tr>
<tr><td><code>top</code></td><td>1</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:linePosition
        */
        public static final int TitlePageIndicator_linePosition = 11;
        /**
          <p>
          @attr description
           Whether or not the selected item is displayed as bold. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:selectedBold
        */
        public static final int TitlePageIndicator_selectedBold = 12;
        /**
          <p>
          @attr description
           Color of the selected title. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:selectedColor
        */
        public static final int TitlePageIndicator_selectedColor = 3;
        /**
          <p>
          @attr description
           Padding between titles when bumping into each other. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:titlePadding
        */
        public static final int TitlePageIndicator_titlePadding = 13;
        /**
          <p>
          @attr description
           Padding between titles and the top of the View. 


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:topPadding
        */
        public static final int TitlePageIndicator_topPadding = 14;
        /** Attributes that can be used with a UnderlinePageIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_android_background android:background}</code></td><td> View background </td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_fadeDelay com.bmob.im.demo:fadeDelay}</code></td><td> Length of the delay to fade the indicator.</td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_fadeLength com.bmob.im.demo:fadeLength}</code></td><td> Length of the indicator fade to transparent.</td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_fades com.bmob.im.demo:fades}</code></td><td> Whether or not the selected indicator fades.</td></tr>
           <tr><td><code>{@link #UnderlinePageIndicator_selectedColor com.bmob.im.demo:selectedColor}</code></td><td> Color of the selected line that represents the current page.</td></tr>
           </table>
           @see #UnderlinePageIndicator_android_background
           @see #UnderlinePageIndicator_fadeDelay
           @see #UnderlinePageIndicator_fadeLength
           @see #UnderlinePageIndicator_fades
           @see #UnderlinePageIndicator_selectedColor
         */
        public static final int[] UnderlinePageIndicator = {
            0x010100d4, 0x7f010007, 0x7f01001c, 0x7f01001d,
            0x7f01001e
        };
        /**
          <p>
          @attr description
           View background 
          <p>This corresponds to the global attribute
          resource symbol {@link android.R.attr#background}.
          @attr name android:background
        */
        public static final int UnderlinePageIndicator_android_background = 0;
        /**
          <p>
          @attr description
           Length of the delay to fade the indicator. 


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:fadeDelay
        */
        public static final int UnderlinePageIndicator_fadeDelay = 3;
        /**
          <p>
          @attr description
           Length of the indicator fade to transparent. 


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:fadeLength
        */
        public static final int UnderlinePageIndicator_fadeLength = 4;
        /**
          <p>
          @attr description
           Whether or not the selected indicator fades. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:fades
        */
        public static final int UnderlinePageIndicator_fades = 2;
        /**
          <p>
          @attr description
           Color of the selected line that represents the current page. 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:selectedColor
        */
        public static final int UnderlinePageIndicator_selectedColor = 1;
        /** Attributes that can be used with a ViewPagerIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiCirclePageIndicatorStyle com.bmob.im.demo:vpiCirclePageIndicatorStyle}</code></td><td> Style of the circle indicator.</td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiIconPageIndicatorStyle com.bmob.im.demo:vpiIconPageIndicatorStyle}</code></td><td> Style of the icon indicator's views.</td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiLinePageIndicatorStyle com.bmob.im.demo:vpiLinePageIndicatorStyle}</code></td><td> Style of the line indicator.</td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiTabPageIndicatorStyle com.bmob.im.demo:vpiTabPageIndicatorStyle}</code></td><td> Style of the tab indicator's tabs.</td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiTitlePageIndicatorStyle com.bmob.im.demo:vpiTitlePageIndicatorStyle}</code></td><td> Style of the title indicator.</td></tr>
           <tr><td><code>{@link #ViewPagerIndicator_vpiUnderlinePageIndicatorStyle com.bmob.im.demo:vpiUnderlinePageIndicatorStyle}</code></td><td> Style of the underline indicator.</td></tr>
           </table>
           @see #ViewPagerIndicator_vpiCirclePageIndicatorStyle
           @see #ViewPagerIndicator_vpiIconPageIndicatorStyle
           @see #ViewPagerIndicator_vpiLinePageIndicatorStyle
           @see #ViewPagerIndicator_vpiTabPageIndicatorStyle
           @see #ViewPagerIndicator_vpiTitlePageIndicatorStyle
           @see #ViewPagerIndicator_vpiUnderlinePageIndicatorStyle
         */
        public static final int[] ViewPagerIndicator = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005
        };
        /**
          <p>
          @attr description
           Style of the circle indicator. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:vpiCirclePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
        /**
          <p>
          @attr description
           Style of the icon indicator's views. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:vpiIconPageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
        /**
          <p>
          @attr description
           Style of the line indicator. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:vpiLinePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
        /**
          <p>
          @attr description
           Style of the tab indicator's tabs. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:vpiTabPageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
        /**
          <p>
          @attr description
           Style of the title indicator. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:vpiTitlePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
        /**
          <p>
          @attr description
           Style of the underline indicator. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.bmob.im.demo:vpiUnderlinePageIndicatorStyle
        */
        public static final int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
    };
}
